DATA:
    DIM: 3 # data dimension
    BATCH_SIZE: 32 # 48 Batch size for a single GPU, could be overwritten by command line argument
    DATA_PATH: ""
    SOURCE_DATA_PATH: "/data/scavone/20cities/patches"
    TARGET_DATA_PATH: "/data/scavone/syntheticMRI/patches"
    NUM_SOURCE_SAMPLES: -1  # all
    NUM_TARGET_SAMPLES: 5000 # train + validation
    TEST_DATA_PATH: "/data/scavone/syntheticMRI/patches"
    DATASET: "mixed_synth_3d" # Dataset name
    IMG_SIZE: [64, 64, 64] # Input image size
    PAD_SIZE: [0, 0, 0]    # [5, 5, 5]
    GROWTH_RANGE: [5, 10]
    NUM_PATCH: 4 # no of patch from each volume
    INTERPOLATION: "bicubic" # Interpolation to resize image (random, bilinear, bicubic)
    PIN_MEMORY: True # Pin CPU memory in DataLoader for more efficient (sometimes) transfer to GPU.
    NUM_WORKERS: 4 # Number of data loading threads
    SEED: 42 # random seed for reproducibility

MODEL:
    # default model parameters
    DROP_PATH_RATE: 0.2
    RESUME: ""
    NUM_CLASSES: 2 # Number of classes, overwritten in data preparation
    DROP_RATE: 0.1 # Dropout rate
    LABEL_SMOOTHING: 0.1 # Label Smoothing
    ADAPTER: group # None, projection, inflation, group

    PRE2D_BACKBONE:
        POSITION_EMBEDDING: sine
        BACKBONE: resnet101
        BACKBONE_INIT_WEIGHTS: ResNet101_Weights
        MASKS: False
        DILATION: False
        NUM_FEATURE_LEVELS: 1
        PADDING_MODE: constant
        MARK_PADDING: False

    ENCODER:
        TYPE: SE-RESNET # SE-RESNET
        CELL_SIZE: 8
        NAME: Squeeze-and-excite-resnet
        EMBED_DIM: 256
        PATCH_SIZE: [4, 4, 4]
        IN_CHANS: 1
        DEPTHS: [4, 4, 16, 4]
        STRIDES: [2, 2, 2, 2]

    DECODER:
        TYPE: def-DETR
        NAME: deformable_DETR
        HIDDEN_DIM: 552
        NHEADS: 6
        ENC_LAYERS: 4
        DEC_LAYERS: 4
        DIM_FEEDFORWARD: 1280
        DROPOUT: 0.0
        ACTIVATION: relu
        NUM_FEATURE_LEVELS: 1
        DEC_N_POINTS: 4
        ENC_N_POINTS: 4
        TWO_STAGE: False
        OBJ_TOKEN: 120
        RLN_TOKEN: 2
        DUMMY_TOKEN: 0
        RLN_ATTN: True
    MATCHER:
        NAME: "Hungarian"   # Graph matcher is not available
        # matching cost
        C_CLASS: 2
        C_NODE: 5

TRAIN:
    START_EPOCH: 0
    EPOCHS: 50
    WARMUP_EPOCHS: 1
    WEIGHT_DECAY: 0.0001
    BASE_LR: 0.00007 # 0.0001
    DOMAIN_LR: 0.00007
    WARMUP_LR: 0.000000001
    MIN_LR: 5e-6
    CLIP_GRAD: 5.0 # Clip gradient norm
    AUTO_RESUME: True # Auto resume from latest checkpoint
    USE_CHECKPOINT: False # could be overwritten by command line argument
    TRAIN_ENCODER: True
    TRAIN_DECODER: True
    DOMAIN_WEIGHTING: [0.05, 0.95]
    IMAGE_ADVERSARIAL: True
    GRAPH_ADVERSARIAL: True
    CONSISTENCY_REGULARIZATION: True
    ALPHA_COEFF: 1.0

    # EDGE_SAMPLING_MODE
    EDGE_SAMPLING_MODE: "up"
    UPSAMPLE_TARGET_DOMAIN: False

    # LR scheduler
    LR_SCHEDULER.NAME: "cosine"
    LR_SCHEDULER.DECAY_EPOCHS: 30 # Epoch interval to decay LR, used in StepLRScheduler
    LR_SCHEDULER.DECAY_RATE: 0.1 # LR decay rate, used in StepLRScheduler

    # Optimizer
    OPTIMIZER.NAME: "adamw"
    OPTIMIZER.EPS: 1e-8 # Optimizer Epsilon
    OPTIMIZER.BETAS: (0.9, 0.999) # Optimizer Betas
    OPTIMIZER.MOMENTUM: 0.9 # SGD momentum
    SAVE_PATH: "/data/scavone/cross-dim_i2g_3d" # save path for the checkpoint, log and val results
    VAL_INTERVAL: 1 # validation interval
    SAVE_VAL: False # save validation data

    # loss
    LOSSES: ["boxes", "class", "cards", "nodes", "edges"]
    NUM_EDGE_SAMPLES: 9999
    EDGE_UPSAMPLING: True # Only combine True with NUM_EDGE_SAMPLES=9999
    EDGE_SAMPLE_RATIO: 0.15
    EDGE_SAMPLE_RATIO_INTERVAL: 0.02
    W_BBOX: 2.0
    W_CLASS: 4.0 # 3.0
    W_CARD: 0.8 # 1.0
    W_NODE: 2.0 # 2.0
    W_EDGE: 6.0 # 4.0
    W_DOMAIN: 1.0   # valore completamente arbitrario

log:
    exp_name: "repl_new-repo"
